services:
  - type: web
    name: oxonom-edu-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://oxonomedu.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
