services:
  - type: web
    name: oxonom-edu-api
    runtime: node
    plan: free
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://oxonomedu.vercel.app
      - key: JWT_SECRET
        value: supersecretjwtkey_eduboard_oxonom_2026
      - key: MONGODB_URI
        value: mongodb+srv://oxobee_admin:OxonomEdu2026DbSecret@oxonomedu.miwnehh.mongodb.net/eduboard?retryWrites=true&w=majority
